version: "3.8"
services:
  app:
    build:
      args:
        user: maks
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: checklistapp
    container_name: checklistapp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - checklistapp

  db:
    image: mariadb:10.3
    container_name: checklistapp-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
     - "3308:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - checklistapp

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
       PMA_ARBITRARY: 1
       PMA_HOST: db
       PMA_USER: ${DB_USERNAME}
       PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - checklistapp

  nginx:
    image: nginx:latest
    container_name: checklistapp-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - checklistapp

networks:
  checklistapp:
    driver: bridge
